let years = [2017, 1986, 2012, 1990, 1975, 1982, 1965, 1974, 2020, 1971, 1978];
let years2 = [1865, 1634];
let names = [
  "Juan",
  "Marta",
  "Jordi",
  "Mónica",
  "Pepe",
  "Irene",
  "Victor",
  "Cristina",
  "Ruben",
  "Claudia",
];

cities = [
  "Übelbach",
  "Älpl",
  "Vienna",
  "graz",
  "Linz",
  "Salzburg",
  "Innsbruck",
  "Klagenfurt",
  "Villach",
  "Wels",
  "St. Pölten",
  "Dornbirn",
  "Steyr",
  "Feldkirch",
  "Bregenz",
  "Wolfsberg",
  "Baden",
  "Leoben",
];

let welcome = "Hello world!";

let movies = [
  {
    title: "The Shawshank Redemption",
    year_of_shoot: 1994,
    director: "Frank Darabont",
    genres: ["Drama"],
    duration: 142,
    rating: 9.3,
    main_characters: ["Andy Dufresne", "Ellis Boyd 'Red' Redding"],
  },
  {
    title: "The Godfather",
    year_of_shoot: 1972,
    director: "Francis Ford Coppola",
    genres: ["Crime", "Drama"],
    duration: 175,
    rating: 9.2,
    main_characters: ["Vito Corleone", "Michael Corleone"],
  },
  {
    title: "The Dark Knight",
    year_of_shoot: 2008,
    director: "Christopher Nolan",
    genres: ["Action", "Crime", "Drama"],
    duration: 152,
    rating: 9.0,
    main_characters: ["Bruce Wayne", "Joker"],
  },
  {
    title: "Pulp Fiction",
    year_of_shoot: 1994,
    director: "Quentin Tarantino",
    genres: ["Crime", "Drama"],
    duration: 154,
    rating: 8.9,
    main_characters: ["Vincent Vega", "Jules Winnfield"],
  },
  {
    title: "The Lord of the Rings: The Return of the King",
    year_of_shoot: 2003,
    director: "Peter Jackson",
    genres: ["Action", "Adventure", "Drama"],
    duration: 201,
    rating: 8.9,
    main_characters: ["Frodo Baggins", "Aragorn"],
  },
  {
    title: "Forrest Gump",
    year_of_shoot: 1994,
    director: "Robert Zemeckis",
    genres: ["Drama", "Romance"],
    duration: 142,
    rating: 8.8,
    main_characters: ["Forrest Gump", "Jenny Curran"],
  },
  {
    title: "Inception",
    year_of_shoot: 2010,
    director: "Christopher Nolan",
    genres: ["Action", "Adventure", "Sci-Fi"],
    duration: 148,
    rating: 8.8,
    main_characters: ["Dom Cobb", "Arthur"],
  },
  {
    title: "Fight Club",
    year_of_shoot: 1999,
    director: "David Fincher",
    genres: ["Drama"],
    duration: 139,
    rating: 8.8,
    main_characters: ["The Narrator", "Tyler Durden"],
  },
  {
    title: "The Matrix",
    year_of_shoot: 1999,
    director: "The Wachowskis",
    genres: ["Action", "Sci-Fi"],
    duration: 136,
    rating: 8.7,
    main_characters: ["Neo", "Morpheus"],
  },
  {
    title: "Goodfellas",
    year_of_shoot: 1990,
    director: "Martin Scorsese",
    genres: ["Biography", "Crime", "Drama"],
    duration: 146,
    rating: 8.7,
    main_characters: ["Henry Hill", "James Conway"],
  },
  {
    title: "The Lord of the Rings: The Fellowship of the Ring",
    year_of_shoot: 2001,
    director: "Peter Jackson",
    genres: ["Action", "Adventure", "Drama"],
    duration: 178,
    rating: 8.8,
    main_characters: ["Frodo Baggins", "Gandalf"],
  },
  {
    title: "Star Wars: Episode V - The Empire Strikes Back",
    year_of_shoot: 1980,
    director: "Irvin Kershner",
    genres: ["Action", "Adventure", "Fantasy"],
    duration: 124,
    rating: 8.7,
    main_characters: ["Luke Skywalker", "Darth Vader"],
  },
  {
    title: "Interstellar",
    year_of_shoot: 2014,
    director: "Christopher Nolan",
    genres: ["Adventure", "Drama", "Sci-Fi"],
    duration: 169,
    rating: 8.6,
    main_characters: ["Cooper", "Murph"],
  },
  {
    title: "The Lord of the Rings: The Two Towers",
    year_of_shoot: 2002,
    director: "Peter Jackson",
    genres: ["Action", "Adventure", "Drama"],
    duration: 179,
    rating: 8.7,
    main_characters: ["Frodo Baggins", "Samwise Gamgee"],
  },
  {
    title: "Se7en",
    year_of_shoot: 1995,
    director: "David Fincher",
    genres: ["Crime", "Drama", "Mystery"],
    duration: 127,
    rating: 8.6,
    main_characters: ["Detective Somerset", "Detective Mills"],
  },
  {
    title: "The Silence of the Lambs",
    year_of_shoot: 1991,
    director: "Jonathan Demme",
    genres: ["Crime", "Drama", "Thriller"],
    duration: 118,
    rating: 8.6,
    main_characters: ["Clarice Starling", "Hannibal Lecter"],
  },
  {
    title: "Saving Private Ryan",
    year_of_shoot: 1998,
    director: "Steven Spielberg",
    genres: ["Drama", "War"],
    duration: 169,
    rating: 8.6,
    main_characters: ["Captain Miller", "Private Ryan"],
  },
  {
    title: "The Green Mile",
    year_of_shoot: 1999,
    director: "Frank Darabont",
    genres: ["Crime", "Drama", "Fantasy"],
    duration: 189,
    rating: 8.6,
    main_characters: ["Paul Edgecomb", "John Coffey"],
  },
  {
    title: "The Usual Suspects",
    year_of_shoot: 1995,
    director: "Bryan Singer",
    genres: ["Crime", "Drama", "Mystery"],
    duration: 106,
    rating: 8.5,
    main_characters: ["Verbal Kint", "Dean Keaton"],
  },
  {
    title: "Schindler's List",
    year_of_shoot: 1993,
    director: "Steven Spielberg",
    genres: ["Biography", "Drama", "History"],
    duration: 195,
    rating: 8.9,
    main_characters: ["Oskar Schindler", "Itzhak Stern"],
  },
  {
    title: "The Lion King",
    year_of_shoot: 1994,
    director: "Roger Allers",
    genres: ["Animation", "Adventure", "Drama"],
    duration: 88,
    rating: 8.5,
    main_characters: ["Simba", "Mufasa"],
  },
  {
    title: "The Prestige",
    year_of_shoot: 2006,
    director: "Christopher Nolan",
    genres: ["Drama", "Mystery", "Sci-Fi"],
    duration: 130,
    rating: 8.5,
    main_characters: ["Robert Angier", "Alfred Borden"],
  },
  {
    title: "The Departed",
    year_of_shoot: 2006,
    director: "Martin Scorsese",
    genres: ["Crime", "Drama", "Thriller"],
    duration: 151,
    rating: 8.5,
    main_characters: ["Billy Costigan", "Colin Sullivan"],
  },
  {
    title: "Gladiator",
    year_of_shoot: 2000,
    director: "Ridley Scott",
    genres: ["Action", "Adventure", "Drama"],
    duration: 155,
    rating: 8.5,
    main_characters: ["Maximus", "Commodus"],
  },
  {
    title: "The Dark Knight Rises",
    year_of_shoot: 2012,
    director: "Christopher Nolan",
    genres: ["Action", "Adventure"],
    duration: 164,
    rating: 8.4,
    main_characters: ["Bruce Wayne", "Selina Kyle"],
  },
  {
    title: "Whiplash",
    year_of_shoot: 2014,
    director: "Damien Chazelle",
    genres: ["Drama", "Music"],
    duration: 106,
    rating: 8.5,
    main_characters: ["Andrew Neiman", "Terence Fletcher"],
  },
  {
    title: "The Intouchables",
    year_of_shoot: 2011,
    director: "Olivier Nakache",
    genres: ["Biography", "Comedy", "Drama"],
    duration: 112,
    rating: 8.5,
    main_characters: ["Driss", "Philippe"],
  },
  {
    title: "The Pianist",
    year_of_shoot: 2002,
    director: "Roman Polanski",
    genres: ["Biography", "Drama", "Music"],
    duration: 150,
    rating: 8.5,
    main_characters: ["Władysław Szpilman", "Captain Wilm Hosenfeld"],
  },
  {
    title: "Terminator 2: Judgment Day",
    year_of_shoot: 1991,
    director: "James Cameron",
    genres: ["Action", "Sci-Fi"],
    duration: 137,
    rating: 8.5,
    main_characters: ["The Terminator", "John Connor"],
  },
  {
    title: "Back to the Future",
    year_of_shoot: 1985,
    director: "Robert Zemeckis",
    genres: ["Adventure", "Comedy", "Sci-Fi"],
    duration: 116,
    rating: 8.5,
    main_characters: ["Marty McFly", "Doc Brown"],
  },
  {
    title: "American History X",
    year_of_shoot: 1998,
    director: "Tony Kaye",
    genres: ["Drama"],
    duration: 119,
    rating: 8.5,
    main_characters: ["Derek Vinyard", "Danny Vinyard"],
  },
  {
    title: "The Green Book",
    year_of_shoot: 2018,
    director: "Peter Farrelly",
    genres: ["Biography", "Comedy", "Drama"],
    duration: 130,
    rating: 8.2,
    main_characters: ["Tony Lip", "Dr. Don Shirley"],
  },
  {
    title: "Parasite",
    year_of_shoot: 2019,
    director: "Bong Joon Ho",
    genres: ["Comedy", "Drama", "Thriller"],
    duration: 132,
    rating: 8.6,
    main_characters: ["Kim Ki-taek", "Kim Ki-woo"],
  },
  {
    title: "Joker",
    year_of_shoot: 2019,
    director: "Todd Phillips",
    genres: ["Crime", "Drama", "Thriller"],
    duration: 122,
    rating: 8.5,
    main_characters: ["Arthur Fleck", "Murray Franklin"],
  },
  {
    title: "Braveheart",
    year_of_shoot: 1995,
    director: "Mel Gibson",
    genres: ["Biography", "Drama", "History"],
    duration: 178,
    rating: 8.4,
    main_characters: ["William Wallace", "Robert the Bruce"],
  },
  {
    title: "The Wolf of Wall Street",
    year_of_shoot: 2013,
    director: "Martin Scorsese",
    genres: ["Biography", "Comedy", "Crime"],
    duration: 180,
    rating: 8.2,
    main_characters: ["Jordan Belfort", "Donnie Azoff"],
  },
  {
    title: "Mad Max: Fury Road",
    year_of_shoot: 2015,
    director: "George Miller",
    genres: ["Action", "Adventure", "Sci-Fi"],
    duration: 120,
    rating: 8.1,
    main_characters: ["Max Rockatansky", "Imperator Furiosa"],
  },
  {
    title: "Spider-Man: Into the Spider-Verse",
    year_of_shoot: 2018,
    director: "Bob Persichetti",
    genres: ["Animation", "Action", "Adventure"],
    duration: 117,
    rating: 8.4,
    main_characters: ["Miles Morales", "Peter B. Parker"],
  },
  {
    title: "Coco",
    year_of_shoot: 2017,
    director: "Lee Unkrich",
    genres: ["Animation", "Adventure", "Comedy"],
    duration: 105,
    rating: 8.4,
    main_characters: ["Miguel", "Héctor"],
  },
  {
    title: "Avengers: Endgame",
    year_of_shoot: 2019,
    director: "Anthony Russo",
    genres: ["Action", "Adventure", "Drama"],
    duration: 181,
    rating: 8.4,
    main_characters: ["Tony Stark", "Steve Rogers"],
  },
  {
    title: "Toy Story 3",
    year_of_shoot: 2010,
    director: "Lee Unkrich",
    genres: ["Animation", "Adventure", "Comedy"],
    duration: 103,
    rating: 8.3,
    main_characters: ["Woody", "Buzz Lightyear"],
  },
  {
    title: "WALL·E",
    year_of_shoot: 2008,
    director: "Andrew Stanton",
    genres: ["Animation", "Adventure", "Family"],
    duration: 98,
    rating: 8.4,
    main_characters: ["WALL·E", "EVE"],
  },
  {
    title: "Finding Nemo",
    year_of_shoot: 2003,
    director: "Andrew Stanton",
    genres: ["Animation", "Adventure", "Comedy"],
    duration: 100,
    rating: 8.1,
    main_characters: ["Marlin", "Dory"],
  },
  {
    title: "Inside Out",
    year_of_shoot: 2015,
    director: "Pete Docter",
    genres: ["Animation", "Adventure", "Comedy"],
    duration: 95,
    rating: 8.1,
    main_characters: ["Joy", "Sadness"],
  },
  {
    title: "The Incredibles",
    year_of_shoot: 2004,
    director: "Brad Bird",
    genres: ["Animation", "Action", "Adventure"],
    duration: 115,
    rating: 8.0,
    main_characters: ["Bob Parr", "Helen Parr"],
  },
  {
    title: "Up",
    year_of_shoot: 2009,
    director: "Pete Docter",
    genres: ["Animation", "Adventure", "Comedy"],
    duration: 96,
    rating: 8.2,
    main_characters: ["Carl Fredricksen", "Russell"],
  },
  {
    title: "Ratatouille",
    year_of_shoot: 2007,
    director: "Brad Bird",
    genres: ["Animation", "Adventure", "Comedy"],
    duration: 111,
    rating: 8.0,
    main_characters: ["Remy", "Linguini"],
  },
  {
    title: "Monsters, Inc.",
    year_of_shoot: 2001,
    director: "Pete Docter",
    genres: ["Animation", "Adventure", "Comedy"],
    duration: 92,
    rating: 8.1,
    main_characters: ["Sully", "Mike Wazowski"],
  },
];
